#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile
from typing import Any


EXPECTED_PACKAGE = "gooroom-session-manager"
EXPECTED_VERSION = "0.3.9+grm3u1+han3u2"
EXPECTED_ENTRIES = 25
EXPECTED_FILES = 10
EXPECTED_ELFS = 4

MULTIARCH_TUPLES = (
    "x86_64-linux-gnu",
    "aarch64-linux-gnu",
)

DYNAMIC_LOADER_SONAME_RE = re.compile(
    r"^ld-linux-[A-Za-z0-9_.-]+\.so(?:\.[0-9]+)+$"
)

# Symbols generated by the compiler, C runtime, linker, or architecture ABI are
# not application API. They are recorded in evidence but excluded from the
# cross-architecture application-symbol set comparison.
RUNTIME_SYMBOL_NAMES = {
    "_DYNAMIC",
    "_GLOBAL_OFFSET_TABLE_",
    "_IO_stdin_used",
    "_ITM_deregisterTMCloneTable",
    "_ITM_registerTMCloneTable",
    "_edata",
    "_end",
    "_fini",
    "_init",
    "_start",
    "__TMC_END__",
    "__bss_end__",
    "__bss_start",
    "__bss_start__",
    "__data_start",
    "__end__",
    "__gmon_start__",
    "__libc_csu_fini",
    "__libc_csu_init",
    "_bss_end__",
    "data_start",
}

RUNTIME_SYMBOL_PREFIXES = (
    "__aarch64_",
    "__aeabi_",
    "__cxa_",
    "__gnu_",
    "__libc_",
    "__stack_chk_",
    "_Unwind_",
)


def run(*args: str) -> str:
    completed = subprocess.run(
        args,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return completed.stdout


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def canonicalize_multiarch_text(value: str) -> str:
    for triplet in MULTIARCH_TUPLES:
        value = value.replace(triplet, "{multiarch}")
    return value


def canonicalize_multiarch_bytes(value: bytes) -> bytes:
    for triplet in MULTIARCH_TUPLES:
        value = value.replace(triplet.encode("ascii"), b"{multiarch}")
    return value


def canonical_path(relative: str) -> str:
    return canonicalize_multiarch_text(relative)


def control(deb: Path) -> dict[str, str]:
    fields = [
        "Package",
        "Source",
        "Version",
        "Architecture",
        "Maintainer",
        "Section",
        "Priority",
        "Depends",
        "Description",
    ]
    result: dict[str, str] = {}
    for field in fields:
        completed = subprocess.run(
            ["dpkg-deb", "-f", str(deb), field],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        result[field] = completed.stdout.rstrip("\n") if completed.returncode == 0 else ""
    return result


def normalize_depends(value: str) -> list[str]:
    return sorted(
        re.sub(r"\s+", " ", item.strip())
        for item in value.split(",")
        if item.strip()
    )


def normalize_cross_arch_depends(value: str) -> list[str]:
    result: list[str] = []
    for dependency in normalize_depends(value):
        if re.fullmatch(r"libc6 \(>= [^)]+\)", dependency):
            dependency = "libc6 (>= {architecture-baseline})"
        result.append(dependency)
    return sorted(result)


def entries(root: Path) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for path in sorted(root.rglob("*")):
        raw_relative = path.relative_to(root).as_posix()
        relative = canonical_path(raw_relative)
        if relative in result:
            raise RuntimeError(
                f"canonical path collision: {raw_relative!r} -> {relative!r}"
            )

        mode = path.lstat().st_mode & 0o7777
        record: dict[str, Any] = {
            "mode": mode,
            "raw_path": raw_relative,
        }

        if path.is_symlink():
            record.update(
                kind="symlink",
                target=canonicalize_multiarch_text(os.readlink(path)),
            )
        elif path.is_dir():
            record.update(kind="dir")
        elif path.is_file():
            raw = path.read_bytes()
            if raw[:4] == b"\x7fELF":
                record.update(
                    kind="elf",
                    raw_sha256=sha256_bytes(raw),
                    raw_size=len(raw),
                )
            else:
                canonical = canonicalize_multiarch_bytes(raw)
                record.update(
                    kind="file",
                    raw_sha256=sha256_bytes(raw),
                    raw_size=len(raw),
                    canonical_sha256=sha256_bytes(canonical),
                    canonical_size=len(canonical),
                    multiarch_text_normalized=(canonical != raw),
                )
        else:
            record.update(kind="other")

        result[relative] = record
    return result


def comparable_entry(record: dict[str, Any]) -> dict[str, Any]:
    kind = record["kind"]
    result: dict[str, Any] = {
        "kind": kind,
        "mode": record["mode"],
    }
    if kind == "symlink":
        result["target"] = record["target"]
    elif kind == "file":
        result["canonical_sha256"] = record["canonical_sha256"]
        result["canonical_size"] = record["canonical_size"]
    return result


def elf_machine(path: Path) -> str:
    text = run("readelf", "-hW", str(path))
    match = re.search(r"^\s*Machine:\s*(.+?)\s*$", text, re.MULTILINE)
    if not match:
        raise RuntimeError(f"cannot parse ELF machine: {path}")
    return match.group(1)


def elf_type(path: Path) -> str:
    text = run("readelf", "-hW", str(path))
    match = re.search(r"^\s*Type:\s*(.+?)\s*$", text, re.MULTILINE)
    if not match:
        raise RuntimeError(f"cannot parse ELF type: {path}")
    return match.group(1)


def elf_interpreter(path: Path) -> str:
    text = run("readelf", "-lW", str(path))
    match = re.search(r"Requesting program interpreter:\s*(.*?)\]", text)
    return match.group(1) if match else ""


def needed(path: Path) -> list[str]:
    text = run("readelf", "-dW", str(path))
    return sorted(
        re.findall(r"\(NEEDED\).*Shared library: \[(.*?)\]", text)
    )


def normalize_needed_for_interpreter(
    values: list[str],
    interpreter: str,
) -> tuple[list[str], list[str], bool]:
    """Exclude only this ELF's own runtime loader from DT_NEEDED.

    The observed native Debian ARM64 build serializes
    ``ld-linux-aarch64.so.1`` as both PT_INTERP and DT_NEEDED, while the
    authority AMD64 binary exposes its loader only through PT_INTERP. The
    loader is already verified separately,
    so this function removes only an exact basename match to PT_INTERP. Every
    other DT_NEEDED entry remains subject to exact comparison.
    """
    interpreter_name = Path(interpreter).name if interpreter else ""
    if not interpreter_name or not DYNAMIC_LOADER_SONAME_RE.fullmatch(
        interpreter_name
    ):
        return sorted(values), [], False

    normalized: list[str] = []
    removed: list[str] = []
    policy_ok = True
    for value in values:
        if DYNAMIC_LOADER_SONAME_RE.fullmatch(value):
            if value == interpreter_name:
                removed.append(value)
            else:
                policy_ok = False
                normalized.append(value)
        else:
            normalized.append(value)

    # Multiple loader entries would be unexpected and remain fail-closed.
    if len(removed) > 1:
        policy_ok = False

    return sorted(normalized), sorted(removed), policy_ok


def soname(path: Path) -> str:
    text = run("readelf", "-dW", str(path))
    match = re.search(r"\(SONAME\).*Library soname: \[(.*?)\]", text)
    return match.group(1) if match else ""


def split_symbol_version(value: str) -> tuple[str, str]:
    value = value.split()[0]
    if "@@" in value:
        return tuple(value.split("@@", 1))  # type: ignore[return-value]
    if "@" in value:
        return tuple(value.split("@", 1))  # type: ignore[return-value]
    return value, ""


def dynamic_symbols(path: Path) -> dict[str, list[dict[str, Any]]]:
    text = run("readelf", "--dyn-syms", "--wide", str(path))
    imported: list[dict[str, Any]] = []
    exported: list[dict[str, Any]] = []

    for line in text.splitlines():
        match = re.match(
            r"\s*\d+:\s+[0-9a-fA-F]+\s+\d+\s+"
            r"(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(.+?)\s*$",
            line,
        )
        if not match:
            continue
        symbol_type, binding, visibility, index, raw_name = match.groups()
        base_name, version = split_symbol_version(raw_name)
        if not base_name or base_name == "0":
            continue
        record = {
            "name": base_name,
            "version": version,
            "type": symbol_type,
            "binding": binding,
            "visibility": visibility,
            "defined": index != "UND",
        }
        if index == "UND":
            imported.append(record)
        elif binding in {"GLOBAL", "WEAK"}:
            exported.append(record)

    key = lambda item: (
        item["name"],
        item["version"],
        item["type"],
        item["binding"],
        item["visibility"],
    )
    return {
        "imports": sorted(imported, key=key),
        "exports": sorted(exported, key=key),
    }


def is_runtime_symbol(record: dict[str, Any]) -> bool:
    name = record["name"]
    version = record["version"]
    if version.startswith("GLIBC_"):
        return True
    if name in RUNTIME_SYMBOL_NAMES:
        return True
    return name.startswith(RUNTIME_SYMBOL_PREFIXES)


def semantic_api_names(symbols: dict[str, list[dict[str, Any]]]) -> list[str]:
    names = {
        record["name"]
        for group in (symbols["imports"], symbols["exports"])
        for record in group
        if not is_runtime_symbol(record)
    }
    return sorted(names)


def find_authority_amd64_deb(artifact: Path) -> Path:
    preferred = artifact / "downloads" / "target.deb"
    if preferred.is_file():
        return preferred

    matches = list(artifact.rglob("target.deb"))
    if len(matches) != 1:
        raise RuntimeError(
            f"expected one target.deb in authority artifact, got {len(matches)}"
        )
    return matches[0]


def verify_semantic_authority(path: Path) -> dict[str, Any]:
    authority = json.loads(path.read_text(encoding="utf-8"))
    required = {
        "schema": 2,
        "package": EXPECTED_PACKAGE,
        "version": EXPECTED_VERSION,
        "target_architecture_for_comparison": "amd64",
        "semantic_binary_equivalent": True,
        "source_reconstruction_semantically_verified": True,
        "arm64_build_allowed": True,
        "package_layer_promotion_allowed": True,
        "exact_binary_equivalent": False,
        "global_exact_reproducibility_claimed": False,
    }
    for field, expected in required.items():
        actual = authority.get(field)
        if actual != expected:
            raise SystemExit(
                f"semantic authority mismatch: {field}={actual!r}, "
                f"expected {expected!r}"
            )

    evidence = authority.get("evidence", {})
    evidence_required = {
        "semantic_equivalent_v3": True,
        "runtime_critical_sections_equal": True,
        "canonical_nm_equal": True,
        "canonical_objdump_equal": True,
        "canonical_readelf_equal": True,
        "storage_serialization_only": True,
    }
    for field, expected in evidence_required.items():
        actual = evidence.get(field)
        if actual != expected:
            raise SystemExit(
                f"semantic evidence mismatch: {field}={actual!r}, "
                f"expected {expected!r}"
            )
    if evidence.get("unexpected_allocated_differences") != []:
        raise SystemExit("semantic authority has unexpected allocated differences")
    if evidence.get("unexpected_section_differences") != []:
        raise SystemExit("semantic authority has unexpected section differences")
    return authority


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--authority-artifact", required=True)
    parser.add_argument("--semantic-authority", required=True)
    parser.add_argument("--arm64-deb", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--reconstruction-run-id", required=True)
    parser.add_argument("--reconstruction-artifact-id", required=True)
    parser.add_argument("--reconstruction-artifact-digest", required=True)
    parser.add_argument("--reconstruction-trigger-sha", required=True)
    parser.add_argument("--source-archive-sha256", required=True)
    parser.add_argument("--native-trigger-sha", required=True)
    parser.add_argument("--bullseye-base-digest", required=True)
    args = parser.parse_args()

    artifact = Path(args.authority_artifact).resolve()
    semantic_authority_path = Path(args.semantic_authority).resolve()
    arm64_deb = Path(args.arm64_deb).resolve()
    output = Path(args.out).resolve()
    output.mkdir(parents=True, exist_ok=True)

    semantic_authority = verify_semantic_authority(semantic_authority_path)
    amd64_deb = find_authority_amd64_deb(artifact)

    amd64_control = control(amd64_deb)
    arm64_control = control(arm64_deb)

    if amd64_control["Package"] != EXPECTED_PACKAGE:
        raise SystemExit("authority AMD64 package has wrong Package")
    if amd64_control["Version"] != EXPECTED_VERSION:
        raise SystemExit("authority AMD64 package has wrong Version")
    if amd64_control["Architecture"] != "amd64":
        raise SystemExit("authority reference package is not amd64")
    if arm64_control["Package"] != EXPECTED_PACKAGE:
        raise SystemExit("native candidate has wrong Package")
    if arm64_control["Version"] != EXPECTED_VERSION:
        raise SystemExit("native candidate has wrong Version")
    if arm64_control["Architecture"] != "arm64":
        raise SystemExit("native candidate is not arm64")

    semantic_fields = [
        "Package",
        "Source",
        "Version",
        "Maintainer",
        "Section",
        "Priority",
        "Description",
    ]
    control_differences = {
        field: {
            "amd64": amd64_control[field],
            "arm64": arm64_control[field],
        }
        for field in semantic_fields
        if amd64_control[field] != arm64_control[field]
    }
    amd64_depends = normalize_cross_arch_depends(amd64_control["Depends"])
    arm64_depends = normalize_cross_arch_depends(arm64_control["Depends"])
    depends_equal = amd64_depends == arm64_depends
    control_ok = not control_differences and depends_equal

    with tempfile.TemporaryDirectory(prefix="session-manager-native-v1-") as temp:
        temp_path = Path(temp)
        amd64_root = temp_path / "amd64"
        arm64_root = temp_path / "arm64"
        amd64_root.mkdir()
        arm64_root.mkdir()
        run("dpkg-deb", "-x", str(amd64_deb), str(amd64_root))
        run("dpkg-deb", "-x", str(arm64_deb), str(arm64_root))

        amd64_entries = entries(amd64_root)
        arm64_entries = entries(arm64_root)
        path_inventory_equal = set(amd64_entries) == set(arm64_entries)

        payload_mismatches: list[dict[str, Any]] = []
        if path_inventory_equal:
            for relative in sorted(amd64_entries):
                left = amd64_entries[relative]
                right = arm64_entries[relative]
                if left["kind"] != right["kind"]:
                    payload_mismatches.append(
                        {
                            "path": relative,
                            "reason": "kind",
                            "amd64": left,
                            "arm64": right,
                        }
                    )
                elif left["kind"] != "elf" and comparable_entry(left) != comparable_entry(right):
                    payload_mismatches.append(
                        {
                            "path": relative,
                            "reason": "canonical-architecture-neutral-payload",
                            "amd64": left,
                            "arm64": right,
                        }
                    )
                elif left["kind"] == "elf" and left["mode"] != right["mode"]:
                    payload_mismatches.append(
                        {
                            "path": relative,
                            "reason": "elf-mode",
                            "amd64": left,
                            "arm64": right,
                        }
                    )
        else:
            payload_mismatches.append(
                {
                    "reason": "path-inventory",
                    "missing_on_arm64": sorted(set(amd64_entries) - set(arm64_entries)),
                    "extra_on_arm64": sorted(set(arm64_entries) - set(amd64_entries)),
                }
            )

        amd64_elf_paths = sorted(
            path for path, record in amd64_entries.items() if record["kind"] == "elf"
        )
        arm64_elf_paths = sorted(
            path for path, record in arm64_entries.items() if record["kind"] == "elf"
        )
        elf_paths_equal = amd64_elf_paths == arm64_elf_paths

        elf_records: list[dict[str, Any]] = []
        elf_semantics_equal = elf_paths_equal
        x86_elf_count = 0

        if elf_paths_equal:
            for relative in arm64_elf_paths:
                amd64_path = amd64_root / amd64_entries[relative]["raw_path"]
                arm64_path = arm64_root / arm64_entries[relative]["raw_path"]

                amd64_machine = elf_machine(amd64_path)
                arm64_machine = elf_machine(arm64_path)
                amd64_type = elf_type(amd64_path)
                arm64_type = elf_type(arm64_path)
                amd64_needed_raw = needed(amd64_path)
                arm64_needed_raw = needed(arm64_path)
                amd64_soname = soname(amd64_path)
                arm64_soname = soname(arm64_path)
                amd64_interpreter = elf_interpreter(amd64_path)
                arm64_interpreter = elf_interpreter(arm64_path)
                (
                    amd64_needed_normalized,
                    amd64_runtime_loader_needed,
                    amd64_needed_policy_ok,
                ) = normalize_needed_for_interpreter(
                    amd64_needed_raw,
                    amd64_interpreter,
                )
                (
                    arm64_needed_normalized,
                    arm64_runtime_loader_needed,
                    arm64_needed_policy_ok,
                ) = normalize_needed_for_interpreter(
                    arm64_needed_raw,
                    arm64_interpreter,
                )
                amd64_symbols = dynamic_symbols(amd64_path)
                arm64_symbols = dynamic_symbols(arm64_path)
                amd64_api = semantic_api_names(amd64_symbols)
                arm64_api = semantic_api_names(arm64_symbols)

                machine_ok = "X86-64" in amd64_machine and "AArch64" in arm64_machine
                if any(token in arm64_machine.lower() for token in ("x86", "80386")):
                    x86_elf_count += 1
                    machine_ok = False
                type_equal = amd64_type == arm64_type
                needed_normalization_policy_ok = (
                    amd64_needed_policy_ok and arm64_needed_policy_ok
                )
                needed_equal = (
                    needed_normalization_policy_ok
                    and amd64_needed_normalized == arm64_needed_normalized
                )
                soname_equal = amd64_soname == arm64_soname
                interpreter_ok = (
                    Path(amd64_interpreter).name == "ld-linux-x86-64.so.2"
                    and Path(arm64_interpreter).name == "ld-linux-aarch64.so.1"
                )
                semantic_api_equal = amd64_api == arm64_api
                record_ok = all(
                    [
                        machine_ok,
                        type_equal,
                        needed_equal,
                        soname_equal,
                        interpreter_ok,
                        semantic_api_equal,
                    ]
                )
                elf_semantics_equal = elf_semantics_equal and record_ok

                elf_records.append(
                    {
                        "path": relative,
                        "ok": record_ok,
                        "machine_ok": machine_ok,
                        "amd64_machine": amd64_machine,
                        "arm64_machine": arm64_machine,
                        "type_equal": type_equal,
                        "amd64_type": amd64_type,
                        "arm64_type": arm64_type,
                        "raw_needed_equal": amd64_needed_raw == arm64_needed_raw,
                        "needed_equal": needed_equal,
                        "needed_equal_after_interpreter_normalization": needed_equal,
                        "needed_normalization_policy_ok": (
                            needed_normalization_policy_ok
                        ),
                        "amd64_needed": amd64_needed_raw,
                        "arm64_needed": arm64_needed_raw,
                        "needed_only_amd64_raw": sorted(
                            set(amd64_needed_raw) - set(arm64_needed_raw)
                        ),
                        "needed_only_arm64_raw": sorted(
                            set(arm64_needed_raw) - set(amd64_needed_raw)
                        ),
                        "amd64_needed_normalized": amd64_needed_normalized,
                        "arm64_needed_normalized": arm64_needed_normalized,
                        "needed_only_amd64_after_normalization": sorted(
                            set(amd64_needed_normalized)
                            - set(arm64_needed_normalized)
                        ),
                        "needed_only_arm64_after_normalization": sorted(
                            set(arm64_needed_normalized)
                            - set(amd64_needed_normalized)
                        ),
                        "amd64_runtime_loader_needed_entries": (
                            amd64_runtime_loader_needed
                        ),
                        "arm64_runtime_loader_needed_entries": (
                            arm64_runtime_loader_needed
                        ),
                        "soname_equal": soname_equal,
                        "amd64_soname": amd64_soname,
                        "arm64_soname": arm64_soname,
                        "interpreter_ok": interpreter_ok,
                        "amd64_interpreter": amd64_interpreter,
                        "arm64_interpreter": arm64_interpreter,
                        "semantic_api_equal": semantic_api_equal,
                        "amd64_semantic_api": amd64_api,
                        "arm64_semantic_api": arm64_api,
                        "semantic_api_only_amd64": sorted(set(amd64_api) - set(arm64_api)),
                        "semantic_api_only_arm64": sorted(set(arm64_api) - set(amd64_api)),
                        "amd64_dynamic_symbols": amd64_symbols,
                        "arm64_dynamic_symbols": arm64_symbols,
                    }
                )

        file_count = sum(record["kind"] in {"file", "elf"} for record in arm64_entries.values())
        counts_ok = all(
            [
                len(arm64_entries) == EXPECTED_ENTRIES,
                file_count == EXPECTED_FILES,
                len(arm64_elf_paths) == EXPECTED_ELFS,
            ]
        )
        non_elf_payload_equal = not payload_mismatches
        verified = all(
            [
                control_ok,
                path_inventory_equal,
                non_elf_payload_equal,
                elf_semantics_equal,
                counts_ok,
                x86_elf_count == 0,
            ]
        )

        summary = {
            "schema": 1,
            "status": "ok" if verified else "failed",
            "package": EXPECTED_PACKAGE,
            "version": EXPECTED_VERSION,
            "architecture": "arm64",
            "arm64_deb": arm64_deb.name,
            "arm64_deb_sha256": sha256(arm64_deb),
            "amd64_authority_deb": str(amd64_deb.relative_to(artifact)),
            "amd64_authority_deb_sha256": sha256(amd64_deb),
            "entry_count": len(arm64_entries),
            "authority_entry_count": len(amd64_entries),
            "file_count": file_count,
            "authority_file_count": sum(
                record["kind"] in {"file", "elf"}
                for record in amd64_entries.values()
            ),
            "elf_count": len(arm64_elf_paths),
            "authority_elf_count": len(amd64_elf_paths),
            "x86_elf_count": x86_elf_count,
            "path_inventory_equal": path_inventory_equal,
            "non_elf_payload_equal_after_multiarch_normalization": non_elf_payload_equal,
            "elf_semantics_equal": elf_semantics_equal,
            "control_semantics_equal": control_ok,
            "source_reconstruction_semantically_verified": True,
            "native_arm64_candidate_verified": verified,
            "package_promotion_allowed": verified,
            "package_promoted": False,
            "iso_assembly_allowed": False,
            "fail_closed": True,
            "provenance": {
                "semantic_authority_sha256": sha256(semantic_authority_path),
                "semantic_analysis_run_id": semantic_authority["analysis_run_id"],
                "reconstruction_run_id": args.reconstruction_run_id,
                "reconstruction_artifact_id": args.reconstruction_artifact_id,
                "reconstruction_artifact_digest": args.reconstruction_artifact_digest,
                "reconstruction_trigger_sha": args.reconstruction_trigger_sha,
                "source_archive_sha256": args.source_archive_sha256,
                "native_trigger_sha": args.native_trigger_sha,
                "runner": "ubuntu-24.04-arm",
                "bullseye_base_digest": args.bullseye_base_digest,
            },
        }

        (output / "summary.json").write_text(
            json.dumps(summary, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        (output / "control-comparison.json").write_text(
            json.dumps(
                {
                    "ok": control_ok,
                    "semantic_field_differences": control_differences,
                    "depends_equal": depends_equal,
                    "amd64_depends_normalized": amd64_depends,
                    "arm64_depends_normalized": arm64_depends,
                    "normalization_policy": {
                        "libc6_minimum_version": "architecture-baseline",
                        "all_other_dependencies": "exact",
                    },
                    "amd64": amd64_control,
                    "arm64": arm64_control,
                },
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        (output / "payload-comparison.json").write_text(
            json.dumps(
                {
                    "ok": path_inventory_equal and non_elf_payload_equal,
                    "path_inventory_equal": path_inventory_equal,
                    "multiarch_normalization": list(MULTIARCH_TUPLES),
                    "amd64_entry_count": len(amd64_entries),
                    "arm64_entry_count": len(arm64_entries),
                    "mismatches": payload_mismatches,
                },
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        (output / "elf-comparison.json").write_text(
            json.dumps(
                {
                    "ok": elf_semantics_equal and x86_elf_count == 0,
                    "paths_equal": elf_paths_equal,
                    "amd64_elf_paths": amd64_elf_paths,
                    "arm64_elf_paths": arm64_elf_paths,
                    "needed_normalization_policy": {
                        "runtime_loader_rule": (
                            "exclude only a DT_NEEDED entry exactly equal to "
                            "the basename of that ELF's PT_INTERP"
                        ),
                        "runtime_loader_name_pattern": (
                            DYNAMIC_LOADER_SONAME_RE.pattern
                        ),
                        "maximum_excluded_entries_per_elf": 1,
                        "all_other_needed_entries": "exact",
                    },
                    "runtime_symbol_policy": {
                        "exclude_glibc_versioned_symbols": True,
                        "excluded_exact_names": sorted(RUNTIME_SYMBOL_NAMES),
                        "excluded_prefixes": list(RUNTIME_SYMBOL_PREFIXES),
                        "application_and_library_api_names_must_match": True,
                    },
                    "records": elf_records,
                },
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        (output / "package-sha256.txt").write_text(
            f"{sha256(arm64_deb)}  {arm64_deb.name}\n",
            encoding="utf-8",
        )
        (output / "source-provenance.json").write_text(
            json.dumps(summary["provenance"], indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

        print(json.dumps(summary, indent=2, sort_keys=True))
        if not verified:
            raise SystemExit(
                "native ARM64 session-manager candidate verification failed closed"
            )


if __name__ == "__main__":
    main()
